# FROM mcr.microsoft.com/dotnet/aspnet:6.0
# COPY image/ app/
# COPY cicd/commands.sh app/

# WORKDIR /app

# RUN chmod +x commands.sh

# ENTRYPOINT ["./commands.sh"]

FROM mcr.microsoft.com/dotnet/aspnet:6.0

# Copy a single file to test
COPY commands.sh /app/

WORKDIR /app

# List files to confirm the copy
RUN ls -l

ENTRYPOINT ["./commands.sh"]


